name: hello
#these are the jobs insdie the the workflow 

on:
 push: 
  branches: [main]


jobs :
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: say hello to users
        uses: actions/checkout@v4

      - name: hello from github actions 
        run: echo"Hello from GitHub Actions!"






